server:
  port: 8080
  grpc_port: 9090

database:
  url: "postgres://postgres:password@localhost:5432/tickets_db?sslmode=disable"
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "password"
  dbname: "tickets_db"

logging:
  level: "info"
  format: "text"
  output: "stdout"
  include_caller: true
  include_timestamp: true

mode: "debug"
port: "8080" 