// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.0
// source: proto/tickets.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateOrderRequest represents a request to create a new order
type CreateOrderRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConcertSessionId int32                  `protobuf:"varint,2,opt,name=concert_session_id,json=concertSessionId,proto3" json:"concert_session_id,omitempty"`
	NumberOfTickets  int32                  `protobuf:"varint,3,opt,name=number_of_tickets,json=numberOfTickets,proto3" json:"number_of_tickets,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_proto_tickets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tickets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_tickets_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrderRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateOrderRequest) GetConcertSessionId() int32 {
	if x != nil {
		return x.ConcertSessionId
	}
	return 0
}

func (x *CreateOrderRequest) GetNumberOfTickets() int32 {
	if x != nil {
		return x.NumberOfTickets
	}
	return 0
}

// CreateOrderResponse represents the response from creating an order
type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int32                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	TicketIds     []string               `protobuf:"bytes,3,rep,name=ticket_ids,json=ticketIds,proto3" json:"ticket_ids,omitempty"`
	TotalPrice    float64                `protobuf:"fixed64,4,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_proto_tickets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tickets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_tickets_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrderResponse) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CreateOrderResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateOrderResponse) GetTicketIds() []string {
	if x != nil {
		return x.TicketIds
	}
	return nil
}

func (x *CreateOrderResponse) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *CreateOrderResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// GetOrderRequest represents a request to retrieve an order
type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int32                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_proto_tickets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tickets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_tickets_proto_rawDescGZIP(), []int{2}
}

func (x *GetOrderRequest) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

// GetOrderResponse represents the response from retrieving an order
type GetOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderResponse) Reset() {
	*x = GetOrderResponse{}
	mi := &file_proto_tickets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse) ProtoMessage() {}

func (x *GetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tickets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse.ProtoReflect.Descriptor instead.
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_tickets_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

// ListOrdersRequest represents a request to list orders
type ListOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersRequest) Reset() {
	*x = ListOrdersRequest{}
	mi := &file_proto_tickets_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest) ProtoMessage() {}

func (x *ListOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tickets_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return file_proto_tickets_proto_rawDescGZIP(), []int{4}
}

func (x *ListOrdersRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListOrdersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListOrdersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// ListOrdersResponse represents the response from listing orders
type ListOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersResponse) Reset() {
	*x = ListOrdersResponse{}
	mi := &file_proto_tickets_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersResponse) ProtoMessage() {}

func (x *ListOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tickets_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListOrdersResponse) Descriptor() ([]byte, []int) {
	return file_proto_tickets_proto_rawDescGZIP(), []int{5}
}

func (x *ListOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *ListOrdersResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListOrdersResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListOrdersResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// GetConcertSessionRequest represents a request to retrieve a concert session
type GetConcertSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     int32                  `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConcertSessionRequest) Reset() {
	*x = GetConcertSessionRequest{}
	mi := &file_proto_tickets_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConcertSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConcertSessionRequest) ProtoMessage() {}

func (x *GetConcertSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tickets_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConcertSessionRequest.ProtoReflect.Descriptor instead.
func (*GetConcertSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_tickets_proto_rawDescGZIP(), []int{6}
}

func (x *GetConcertSessionRequest) GetSessionId() int32 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

// GetConcertSessionResponse represents the response from retrieving a concert session
type GetConcertSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *ConcertSession        `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConcertSessionResponse) Reset() {
	*x = GetConcertSessionResponse{}
	mi := &file_proto_tickets_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConcertSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConcertSessionResponse) ProtoMessage() {}

func (x *GetConcertSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tickets_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConcertSessionResponse.ProtoReflect.Descriptor instead.
func (*GetConcertSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_tickets_proto_rawDescGZIP(), []int{7}
}

func (x *GetConcertSessionResponse) GetSession() *ConcertSession {
	if x != nil {
		return x.Session
	}
	return nil
}

// ListConcertSessionsRequest represents a request to list concert sessions
type ListConcertSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConcertSessionsRequest) Reset() {
	*x = ListConcertSessionsRequest{}
	mi := &file_proto_tickets_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConcertSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConcertSessionsRequest) ProtoMessage() {}

func (x *ListConcertSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tickets_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConcertSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListConcertSessionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_tickets_proto_rawDescGZIP(), []int{8}
}

func (x *ListConcertSessionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListConcertSessionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// ListConcertSessionsResponse represents the response from listing concert sessions
type ListConcertSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*ConcertSession      `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConcertSessionsResponse) Reset() {
	*x = ListConcertSessionsResponse{}
	mi := &file_proto_tickets_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConcertSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConcertSessionsResponse) ProtoMessage() {}

func (x *ListConcertSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tickets_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConcertSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListConcertSessionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_tickets_proto_rawDescGZIP(), []int{9}
}

func (x *ListConcertSessionsResponse) GetSessions() []*ConcertSession {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *ListConcertSessionsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListConcertSessionsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListConcertSessionsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// GetAvailableTicketsRequest represents a request to get available tickets
type GetAvailableTicketsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     int32                  `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableTicketsRequest) Reset() {
	*x = GetAvailableTicketsRequest{}
	mi := &file_proto_tickets_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableTicketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableTicketsRequest) ProtoMessage() {}

func (x *GetAvailableTicketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tickets_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableTicketsRequest.ProtoReflect.Descriptor instead.
func (*GetAvailableTicketsRequest) Descriptor() ([]byte, []int) {
	return file_proto_tickets_proto_rawDescGZIP(), []int{10}
}

func (x *GetAvailableTicketsRequest) GetSessionId() int32 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *GetAvailableTicketsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// GetAvailableTicketsResponse represents the response from getting available tickets
type GetAvailableTicketsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Tickets        []*Ticket              `protobuf:"bytes,1,rep,name=tickets,proto3" json:"tickets,omitempty"`
	TotalAvailable int32                  `protobuf:"varint,2,opt,name=total_available,json=totalAvailable,proto3" json:"total_available,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetAvailableTicketsResponse) Reset() {
	*x = GetAvailableTicketsResponse{}
	mi := &file_proto_tickets_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableTicketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableTicketsResponse) ProtoMessage() {}

func (x *GetAvailableTicketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tickets_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableTicketsResponse.ProtoReflect.Descriptor instead.
func (*GetAvailableTicketsResponse) Descriptor() ([]byte, []int) {
	return file_proto_tickets_proto_rawDescGZIP(), []int{11}
}

func (x *GetAvailableTicketsResponse) GetTickets() []*Ticket {
	if x != nil {
		return x.Tickets
	}
	return nil
}

func (x *GetAvailableTicketsResponse) GetTotalAvailable() int32 {
	if x != nil {
		return x.TotalAvailable
	}
	return 0
}

// Order represents an order in the system
type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	TotalPrice    float64                `protobuf:"fixed64,3,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Items         []*OrderItem           `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_proto_tickets_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tickets_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_proto_tickets_proto_rawDescGZIP(), []int{12}
}

func (x *Order) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Order) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Order) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *Order) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Order) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// OrderItem represents an item in an order
type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TicketId      string                 `protobuf:"bytes,2,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Ticket        *Ticket                `protobuf:"bytes,4,opt,name=ticket,proto3" json:"ticket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_proto_tickets_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tickets_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_proto_tickets_proto_rawDescGZIP(), []int{13}
}

func (x *OrderItem) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderItem) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *OrderItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderItem) GetTicket() *Ticket {
	if x != nil {
		return x.Ticket
	}
	return nil
}

// ConcertSession represents a concert session
type ConcertSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ConcertId     int32                  `protobuf:"varint,2,opt,name=concert_id,json=concertId,proto3" json:"concert_id,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Venue         string                 `protobuf:"bytes,5,opt,name=venue,proto3" json:"venue,omitempty"`
	NumberOfSeats int32                  `protobuf:"varint,6,opt,name=number_of_seats,json=numberOfSeats,proto3" json:"number_of_seats,omitempty"`
	Price         float64                `protobuf:"fixed64,7,opt,name=price,proto3" json:"price,omitempty"`
	Concert       *Concert               `protobuf:"bytes,8,opt,name=concert,proto3" json:"concert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConcertSession) Reset() {
	*x = ConcertSession{}
	mi := &file_proto_tickets_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConcertSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConcertSession) ProtoMessage() {}

func (x *ConcertSession) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tickets_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConcertSession.ProtoReflect.Descriptor instead.
func (*ConcertSession) Descriptor() ([]byte, []int) {
	return file_proto_tickets_proto_rawDescGZIP(), []int{14}
}

func (x *ConcertSession) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ConcertSession) GetConcertId() int32 {
	if x != nil {
		return x.ConcertId
	}
	return 0
}

func (x *ConcertSession) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ConcertSession) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *ConcertSession) GetVenue() string {
	if x != nil {
		return x.Venue
	}
	return ""
}

func (x *ConcertSession) GetNumberOfSeats() int32 {
	if x != nil {
		return x.NumberOfSeats
	}
	return 0
}

func (x *ConcertSession) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ConcertSession) GetConcert() *Concert {
	if x != nil {
		return x.Concert
	}
	return nil
}

// Concert represents a concert
type Concert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Concert) Reset() {
	*x = Concert{}
	mi := &file_proto_tickets_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Concert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Concert) ProtoMessage() {}

func (x *Concert) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tickets_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Concert.ProtoReflect.Descriptor instead.
func (*Concert) Descriptor() ([]byte, []int) {
	return file_proto_tickets_proto_rawDescGZIP(), []int{15}
}

func (x *Concert) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Concert) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Concert) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Concert) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Concert) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Ticket represents a ticket
type Ticket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SessionId     int32                  `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ticket) Reset() {
	*x = Ticket{}
	mi := &file_proto_tickets_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ticket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ticket) ProtoMessage() {}

func (x *Ticket) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tickets_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ticket.ProtoReflect.Descriptor instead.
func (*Ticket) Descriptor() ([]byte, []int) {
	return file_proto_tickets_proto_rawDescGZIP(), []int{16}
}

func (x *Ticket) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Ticket) GetSessionId() int32 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *Ticket) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_tickets_proto protoreflect.FileDescriptor

const file_proto_tickets_proto_rawDesc = "" +
	"\n" +
	"\x13proto/tickets.proto\x12\atickets\x1a\x1fgoogle/protobuf/timestamp.proto\"\x87\x01\n" +
	"\x12CreateOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12,\n" +
	"\x12concert_session_id\x18\x02 \x01(\x05R\x10concertSessionId\x12*\n" +
	"\x11number_of_tickets\x18\x03 \x01(\x05R\x0fnumberOfTickets\"\xc3\x01\n" +
	"\x13CreateOrderResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x05R\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"ticket_ids\x18\x03 \x03(\tR\tticketIds\x12\x1f\n" +
	"\vtotal_price\x18\x04 \x01(\x01R\n" +
	"totalPrice\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\",\n" +
	"\x0fGetOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x05R\aorderId\"8\n" +
	"\x10GetOrderResponse\x12$\n" +
	"\x05order\x18\x01 \x01(\v2\x0e.tickets.OrderR\x05order\"]\n" +
	"\x11ListOrdersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\x8e\x01\n" +
	"\x12ListOrdersResponse\x12&\n" +
	"\x06orders\x18\x01 \x03(\v2\x0e.tickets.OrderR\x06orders\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"9\n" +
	"\x18GetConcertSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x05R\tsessionId\"N\n" +
	"\x19GetConcertSessionResponse\x121\n" +
	"\asession\x18\x01 \x01(\v2\x17.tickets.ConcertSessionR\asession\"M\n" +
	"\x1aListConcertSessionsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\xa4\x01\n" +
	"\x1bListConcertSessionsResponse\x123\n" +
	"\bsessions\x18\x01 \x03(\v2\x17.tickets.ConcertSessionR\bsessions\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"Q\n" +
	"\x1aGetAvailableTicketsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x05R\tsessionId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"q\n" +
	"\x1bGetAvailableTicketsResponse\x12)\n" +
	"\atickets\x18\x01 \x03(\v2\x0f.tickets.TicketR\atickets\x12'\n" +
	"\x0ftotal_available\x18\x02 \x01(\x05R\x0etotalAvailable\"\xb5\x01\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1f\n" +
	"\vtotal_price\x18\x03 \x01(\x01R\n" +
	"totalPrice\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12(\n" +
	"\x05items\x18\x05 \x03(\v2\x12.tickets.OrderItemR\x05items\"w\n" +
	"\tOrderItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1b\n" +
	"\tticket_id\x18\x02 \x01(\tR\bticketId\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12'\n" +
	"\x06ticket\x18\x04 \x01(\v2\x0f.tickets.TicketR\x06ticket\"\xb1\x02\n" +
	"\x0eConcertSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1d\n" +
	"\n" +
	"concert_id\x18\x02 \x01(\x05R\tconcertId\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x14\n" +
	"\x05venue\x18\x05 \x01(\tR\x05venue\x12&\n" +
	"\x0fnumber_of_seats\x18\x06 \x01(\x05R\rnumberOfSeats\x12\x14\n" +
	"\x05price\x18\a \x01(\x01R\x05price\x12*\n" +
	"\aconcert\x18\b \x01(\v2\x10.tickets.ConcertR\aconcert\"\xa6\x01\n" +
	"\aConcert\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"O\n" +
	"\x06Ticket\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\x05R\tsessionId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status2\x82\x04\n" +
	"\x0eTicketsService\x12H\n" +
	"\vCreateOrder\x12\x1b.tickets.CreateOrderRequest\x1a\x1c.tickets.CreateOrderResponse\x12?\n" +
	"\bGetOrder\x12\x18.tickets.GetOrderRequest\x1a\x19.tickets.GetOrderResponse\x12E\n" +
	"\n" +
	"ListOrders\x12\x1a.tickets.ListOrdersRequest\x1a\x1b.tickets.ListOrdersResponse\x12Z\n" +
	"\x11GetConcertSession\x12!.tickets.GetConcertSessionRequest\x1a\".tickets.GetConcertSessionResponse\x12`\n" +
	"\x13ListConcertSessions\x12#.tickets.ListConcertSessionsRequest\x1a$.tickets.ListConcertSessionsResponse\x12`\n" +
	"\x13GetAvailableTickets\x12#.tickets.GetAvailableTicketsRequest\x1a$.tickets.GetAvailableTicketsResponseB\rZ\vtickets/apib\x06proto3"

var (
	file_proto_tickets_proto_rawDescOnce sync.Once
	file_proto_tickets_proto_rawDescData []byte
)

func file_proto_tickets_proto_rawDescGZIP() []byte {
	file_proto_tickets_proto_rawDescOnce.Do(func() {
		file_proto_tickets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tickets_proto_rawDesc), len(file_proto_tickets_proto_rawDesc)))
	})
	return file_proto_tickets_proto_rawDescData
}

var file_proto_tickets_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_tickets_proto_goTypes = []any{
	(*CreateOrderRequest)(nil),          // 0: tickets.CreateOrderRequest
	(*CreateOrderResponse)(nil),         // 1: tickets.CreateOrderResponse
	(*GetOrderRequest)(nil),             // 2: tickets.GetOrderRequest
	(*GetOrderResponse)(nil),            // 3: tickets.GetOrderResponse
	(*ListOrdersRequest)(nil),           // 4: tickets.ListOrdersRequest
	(*ListOrdersResponse)(nil),          // 5: tickets.ListOrdersResponse
	(*GetConcertSessionRequest)(nil),    // 6: tickets.GetConcertSessionRequest
	(*GetConcertSessionResponse)(nil),   // 7: tickets.GetConcertSessionResponse
	(*ListConcertSessionsRequest)(nil),  // 8: tickets.ListConcertSessionsRequest
	(*ListConcertSessionsResponse)(nil), // 9: tickets.ListConcertSessionsResponse
	(*GetAvailableTicketsRequest)(nil),  // 10: tickets.GetAvailableTicketsRequest
	(*GetAvailableTicketsResponse)(nil), // 11: tickets.GetAvailableTicketsResponse
	(*Order)(nil),                       // 12: tickets.Order
	(*OrderItem)(nil),                   // 13: tickets.OrderItem
	(*ConcertSession)(nil),              // 14: tickets.ConcertSession
	(*Concert)(nil),                     // 15: tickets.Concert
	(*Ticket)(nil),                      // 16: tickets.Ticket
	(*timestamppb.Timestamp)(nil),       // 17: google.protobuf.Timestamp
}
var file_proto_tickets_proto_depIdxs = []int32{
	17, // 0: tickets.CreateOrderResponse.created_at:type_name -> google.protobuf.Timestamp
	12, // 1: tickets.GetOrderResponse.order:type_name -> tickets.Order
	12, // 2: tickets.ListOrdersResponse.orders:type_name -> tickets.Order
	14, // 3: tickets.GetConcertSessionResponse.session:type_name -> tickets.ConcertSession
	14, // 4: tickets.ListConcertSessionsResponse.sessions:type_name -> tickets.ConcertSession
	16, // 5: tickets.GetAvailableTicketsResponse.tickets:type_name -> tickets.Ticket
	17, // 6: tickets.Order.created_at:type_name -> google.protobuf.Timestamp
	13, // 7: tickets.Order.items:type_name -> tickets.OrderItem
	16, // 8: tickets.OrderItem.ticket:type_name -> tickets.Ticket
	17, // 9: tickets.ConcertSession.start_time:type_name -> google.protobuf.Timestamp
	17, // 10: tickets.ConcertSession.end_time:type_name -> google.protobuf.Timestamp
	15, // 11: tickets.ConcertSession.concert:type_name -> tickets.Concert
	17, // 12: tickets.Concert.created_at:type_name -> google.protobuf.Timestamp
	0,  // 13: tickets.TicketsService.CreateOrder:input_type -> tickets.CreateOrderRequest
	2,  // 14: tickets.TicketsService.GetOrder:input_type -> tickets.GetOrderRequest
	4,  // 15: tickets.TicketsService.ListOrders:input_type -> tickets.ListOrdersRequest
	6,  // 16: tickets.TicketsService.GetConcertSession:input_type -> tickets.GetConcertSessionRequest
	8,  // 17: tickets.TicketsService.ListConcertSessions:input_type -> tickets.ListConcertSessionsRequest
	10, // 18: tickets.TicketsService.GetAvailableTickets:input_type -> tickets.GetAvailableTicketsRequest
	1,  // 19: tickets.TicketsService.CreateOrder:output_type -> tickets.CreateOrderResponse
	3,  // 20: tickets.TicketsService.GetOrder:output_type -> tickets.GetOrderResponse
	5,  // 21: tickets.TicketsService.ListOrders:output_type -> tickets.ListOrdersResponse
	7,  // 22: tickets.TicketsService.GetConcertSession:output_type -> tickets.GetConcertSessionResponse
	9,  // 23: tickets.TicketsService.ListConcertSessions:output_type -> tickets.ListConcertSessionsResponse
	11, // 24: tickets.TicketsService.GetAvailableTickets:output_type -> tickets.GetAvailableTicketsResponse
	19, // [19:25] is the sub-list for method output_type
	13, // [13:19] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_tickets_proto_init() }
func file_proto_tickets_proto_init() {
	if File_proto_tickets_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tickets_proto_rawDesc), len(file_proto_tickets_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tickets_proto_goTypes,
		DependencyIndexes: file_proto_tickets_proto_depIdxs,
		MessageInfos:      file_proto_tickets_proto_msgTypes,
	}.Build()
	File_proto_tickets_proto = out.File
	file_proto_tickets_proto_goTypes = nil
	file_proto_tickets_proto_depIdxs = nil
}
